mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedules.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('schedules/images/favicon.ico')))
]

schedules/urls.py
from django.urls import path
from . import views

app_name = 'schedules'
urlpatterns = [
    path('', views.intro, name='intro' ),
    path('main', views.index, name='index' ),
    path('main2', views.index2, name='index2' ),
    path('carousel', views.carousel, name='carousel'),
    path('introduce', views.introduce, name='introduce'),
]

schedules/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=1000)
    link = models.CharField(max_length=1000)
    image = models.CharField(max_length=1000)
    homepage = models.CharField(max_length=1000)
    time = models.DateTimeField()
    
    class Meta:
        db_table = 'article'


    def __str__(self):
        return self.title

class Job(models.Model):
    id = models.IntegerField(primary_key=True)
    company = models.CharField(max_length=1000)
    title = models.CharField(max_length=1000)
    link = models.CharField(max_length=1000)
    end_date = models.CharField(max_length=1000)
    time = models.DateTimeField()
    class Meta:
        db_table = 'job'
    def __str__(self):
        return self.title

schedules/views.py
from django.shortcuts import render
from .models import Article, Job
from django.core.paginator import Paginator

# Create your views here.

def intro(request):
    return render(request, 'schedules/intro.html')

def index(request):
    articles = Article.objects.all().order_by('id')
    article_paginator = Paginator(articles,5)
    article_page = request.GET.get('page')
    article_obj = article_paginator.get_page(article_page)

    alltime_jobs = Job.objects.filter(end_date='상시채용').order_by('id')
    normal_jobs = Job.objects.exclude(end_date='상시채용').order_by('id')
    job_paginator = Paginator(normal_jobs, 10)
    job_page = request.GET.get('page')
    job_obj = job_paginator.get_page(job_page)
    context = { 'alltime_jobs':alltime_jobs, 'article_obj': article_obj, 'job_obj': job_obj}
    return render(request, 'schedules/index.html',context)

def index2(request):
    articles = Article.objects.all().order_by('id')
    article_paginator = Paginator(articles,5)
    article_page = request.GET.get('page')
    article_obj = article_paginator.get_page(article_page)

    alltime_jobs = Job.objects.filter(end_date='상시채용').order_by('id')
    normal_jobs = Job.objects.exclude(end_date='상시채용').order_by('id')
    job_paginator = Paginator(normal_jobs, 10)
    job_page = request.GET.get('page')
    job_obj = job_paginator.get_page(job_page)
    context = { 'alltime_jobs':alltime_jobs, 'article_obj': article_obj, 'job_obj': job_obj}
    return render(request, 'schedules/index2.html',context)

def carousel(request):
    first = Article.objects.filter(homepage='boannews').order_by('id').first()
    second = Article.objects.filter(homepage='TheHackerNews').order_by('id').first()
    third = Article.objects.filter(homepage='dailysecu').order_by('id').first()
    context = { 'first':first, 'second':second, 'third': third}
    return render(request, 'schedules/carousel.html', context)

def introduce(request):
    return render(request, 'schedules/introduce.html')

schedules/templates/schedules/alltime_jobs.html
{% for job in alltime_jobs %}
<a
href="{{ job.link }}"
target="_blank"
class="list-group-item list-group-item-action"
>
<div class="d-flex w-100 justify-content-between">
<h5 id="news_title" class="mb-1">{{ job.title }}</h5>
<small class="text-muted">{{ job.company }}</small>
</div>
<p class="mb-1">마감 기한 : {{ job.end_date }}</p>
<!-- <small class="text-muted">{{ job.time }}</small> -->
</a>

{% endfor %}

schedules/templates/schedules/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link href="https://fonts.googleapis.com/css?family=Jua&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet">
   <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <style>
      .container{
        width:75%;
        height:80%;
        background-color: white;
        border-radius: 30px;
      }
      .carousel {
        background-color: black;
        
      }
      .carousel-inner > .carousel-item > a > img {
      
      width: 65%;
      margin: auto;
      height: 450px;
      border-radius: 3px;
      } 
      .carousel-caption > h4 {
        font-family: Noto Sans KR;
      }
      .carousel-caption {
        background-color: black;
        opacity: 0.7;
      }
      .row {
          width: 60%;
          height:100%;
          margin: auto;
          text-align: center;
          justify-content: center;
          margin-top: -50px;
          display: flex;
          background-color: rgba( 0, 0, 0, 0.8 );
      }
      .list-group {
        
        background-color: white;
      }
      .topbar {
        margin-top: 15px;
      }
      .top-title {
        margin-left: 30px;
        font-family: Nanum Gothic;
      }
      .blank {
        height:20px;
        margin-bottom: 10px;
      }
      .tab-content {
        width:95%;
        margin:auto;
      }

      body {
        background-image: url('/static/schedules/images/2.jpg');
        background-size: contain;
        height:100%;
        backdrop-filter: grayscale(0.8);
        
      }
      h1 {
        color: whitesmoke;
      }
      @keyframes fadein {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
      }
      
      #news_title {
        font-family: Noto Sans KR;
      }
      .nav-pills .nav-link.active, .nav-pills .show>.nav-link {
        background-color: #343a40;
      }
      .thumbbox {
        border-radius: 30px;
      }
      .thumbnail {
        width: 200px;
        height: 125px;
      }
      #topButton {position: fixed; right: 5%; bottom: 50px; z-index: 999;}
      .titlebox {
        margin-top: 20px;
        margin-left: 20px;
      }

      .navbar {
        position: sticky; 
        top:0; 
        width: 100%; 
        z-index: 999;
        opacity: 0.9;
        font-family: 'Noto Sans KR';
        font-size: larger;
      }

      .pagination {
        font-size: xx-large;
      }
      .card {
        max-height:344px;
        width: 80%;
        font-family: Noto Sans KR;
        animation: fadein 2s;
      }
      .card:hover {
        opacity: 0.8;
        cursor: grab;
      }
      .card > img {
        height: 229px;
      }
      .card > h5 {
        font-weight:bold;
      }
      
      i {
        color:darkslategrey
      }

      .carousel-box {
        height:100%;
        margin-top: -100px;
        margin-bottom: 100px;
        animation: fadein 3s;
      }

      .intro-box {
        margin :auto;
        text-align: center;
        align-items: center;
        justify-content: center;
        display: flex;
        border-radius: 5px;
        border: 5px whitesmoke;
        width: 70%;
        height: 100%;
        background-color: snow;
        animation: fadein 3s;
      }
      .pagination {
        margin-left: 20px;
      }
    </style>
  </head>

  <body>
    {% include 'schedules/navbar.html' %}
    <h1><pre></pre> <pre> </pre></h1>
    {% comment %} <div><title>Hello, world!</title></div> {% endcomment %}

    {% block content %} {% endblock content %}

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
      integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
      integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

schedules/templates/schedules/carousel.html
{% extends 'schedules/base.html' %}
{% load static %}

{% block content %}
<div class="carousel-box">
    <div class="row">
        <div class="" style="text-align: center; margin-top: 60px; margin-bottom: 40px;">
            <h1 style="font-family: Do Hyeon; color: whitesmoke;">플랫폼별 상위 기사 톺아보기</h1>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active data-bs-interval="1500"">
                    <a href="{{ first.link }}" target="_blank">
                        <img src="{{ first.image }}" class="d-block " alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h4>{{ first.title }}</h4>
                        <p>보안뉴스 최신기사</p>
                    </div>
                </div>
                <div class="carousel-item data-bs-interval="1500"">
                    <a href="{{ second.link }}" target="_blank">
                        <img src="{{ second.image }}" class="d-block " alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h4>{{ second.title }}</h4>
                        <p>더해커뉴스 최신기사</p>
                    </div>
                </div>
                <div class="carousel-item data-bs-interval="1500"">
                    <a href="{{ third.link }}" target="_blank">
                        <img src="{{ third.image }}" class="d-block " alt="...">
                    </a>
                    <div class="carousel-caption d-none d-md-block">
                        <h4>{{ third.title }}</h4>
                        <p>데일리시큐 최신기사</p>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div class="btn-group mt-2 mb-4" role="group" aria-label="actionButtons">
            <a href="{% url 'schedules:index' %}" class="d-block btn btn-outline-light"><h4 style="font-family: 'Jua';"> <i class="fas fa-newspaper" style="color:whitesmoke"></i> 더 많은 기사 보러가기</h4></a>
            <a href="{% url 'schedules:index2' %}" class="d-block btn btn-outline-light"><h4 style="font-family: 'Jua';"> 채용공고 보러가기  <i
                    class="fas fa-users" style="color: whitesmoke;"></i></h4></a>
        </div>
    </div>
<script type="text/javascript">
    localStorage.clear()
</script>
</div>

{% endblock content%}

schedules/templates/schedules/index.html
{% extends 'schedules/base.html' %} 
{% load static %}

{% block content %}
<div class="container" style="animation: fadein 1.5s">
  <div class="blank"></div>
  <div>
<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="news-tab" data-bs-toggle="tab" data-bs-target="#news" type="button" role="tab"
      aria-controls="news" aria-selected="true"><h4>최신 뉴스 기사</h4></button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="jobs-tab" data-bs-toggle="tab" data-bs-target="#jobs" type="button" role="tab"
      aria-controls="jobs" aria-selected="false"><h4>채용 공고 정보</h4></button>
  </li>
</ul>
</div>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="news" role="tabpanel" aria-labelledby="news-tab">
    {% include 'schedules/paged_news.html' %}
    </div>
  <div class="tab-pane fade" id="jobs" role="tabpanel" aria-labelledby="jobs-tab">{% include 'schedules/jobs_group.html' %}</div>
</div>

<div class="blank"></div>
<div id="topButton" style="cursor: pointer"><a href="#"><img src="{% static 'schedules/images/topbutton.png' %}" id="topButtonImg"></a></div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script type="text/javascript">
  localStorage.setItem('testvar', 'haha')
  $(function () {
      // for bootstrap 3 use 'shown.bs.tab', for bootstrap 2 use 'shown' in the next line
      $('button[data-bs-toggle="tab"]').on('shown.bs.tab', function (e) {
        // save the latest tab; use cookies if you like 'em better:
        localStorage.setItem('lastTab', $(this).attr('data-bs-target'));
      });

      // go to the latest tab, if it exists:
      var lastTab = localStorage.getItem('lastTab');
      if (lastTab) {
        $('[data-bs-target="' + lastTab + '"]').tab('show');
      }
    });
</script>
{% endblock content %}

schedules/templates/schedules/index2.html
{% extends 'schedules/base.html' %} 
{% load static %}

{% block content %}
<div class="container" style="animation: fadein 1.5s">
  <div class="blank"></div>
  <div>
<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="news-tab" data-bs-toggle="tab" data-bs-target="#news" type="button" role="tab"
      aria-controls="news" aria-selected="false"><h4>최신 뉴스 기사</h4></button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="jobs-tab" data-bs-toggle="tab" data-bs-target="#jobs" type="button" role="tab"
      aria-controls="jobs" aria-selected="true"><h4>채용 공고 정보</h4></button>
  </li>
</ul>
</div>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade " id="news" role="tabpanel" aria-labelledby="news-tab">
    {% include 'schedules/paged_news.html' %}
    </div>
  <div class="tab-pane fade show active" id="jobs" role="tabpanel" aria-labelledby="jobs-tab">
  {% include 'schedules/jobs_group.html' %}
  </div>
</div>

<div class="blank"></div>
<div id="topButton" style="cursor: pointer"><a href="#"><img src="{% static 'schedules/images/topbutton.png' %}" id="topButtonImg"></a></div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script type="text/javascript">
  localStorage.setItem('testvar', 'haha')
  $(function () {
      // for bootstrap 3 use 'shown.bs.tab', for bootstrap 2 use 'shown' in the next line
      $('button[data-bs-toggle="tab"]').on('shown.bs.tab', function (e) {
        // save the latest tab; use cookies if you like 'em better:
        localStorage.setItem('lastTab', $(this).attr('data-bs-target'));
      });

      // go to the latest tab, if it exists:
      var lastTab = localStorage.getItem('lastTab');
      if (lastTab) {
        $('[data-bs-target="' + lastTab + '"]').tab('show');
      }
    });
</script>
{% endblock content %}

schedules/templates/schedules/intro.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Jua&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
    <title>Document</title>
    
    <style>
        body {
            background-color: rgb(142, 180, 227);
        }
    
        ​ html,
        body {
            height: 100%;
            background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
            background-size: 400% 400%;
            animation: gradient 15s ease infinite;
            text-align: center;
            top:50%;
            height:100px;
            margin-top: -50px;
            position:relative;
        }
        @keyframes gradient {
        0% {
            background-position: 0% 50%;
        }
        50% {
            background-position: 100% 50%;
        }
        100% {
            background-position: 0% 50%;
        }
}
        ​ .main {
            height: 100%;
            width: 100%;
            font-family: 'Jua', cursive;
        }
    
        h1, h3{
            font-family: 'Jua', cursive;
            font-weight: 100;
            color: aliceblue;
        
        }
        
        h3{
            margin-bottom: -15px;
        }
        .one {
            animation-duration: 2s;
            animation-name: slideinr;
        }
        .two {
            animation-duration: 4s;
            animation-name: slideinr;
        }
        h1 {
            color:aliceblue;
            font-size: xxx-large;
            animation: fadein 6s;
        }
        @keyframes fadein {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        a {
            font-family: 'Jua';
            animation: fadein 8s;

        }
        @keyframes slideinr {
        from {
            margin-left: 100%;
            width: 300%
        }

        to {
            margin-left: 0%;
            width: 100%;
        }
        }
        @keyframes slideinl {
        from {
            margin-right: 100%;
            width: 300%
        }

        to {
            margin-right: 0%;
            width: 100%;
        }
        }
        @import url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css);


        .bounce {
            animation: bounce 2s infinite;
            animation-delay: 6s;
            height:45px;
        }
        
        @-webkit-keyframes bounce {
            0%, 20%, 50%, 80%, 100% {-webkit-transform: translateY(0);}	
            40% {-webkit-transform: translateY(-30px);}
            60% {-webkit-transform: translateY(-15px);}
        }
        }
        @keyframes bounce {
            0%, 20%, 50%, 80%, 100% {transform: translateY(0);}
            40% {transform: translateY(-30px);}
            60% {transform: translateY(-15px);}
        }

        .logo {
            margin-top: -100px;
            
        }
    </style>
</head>
<body>
    <div class="container" style="margin: auto;">
    <img src="{% static "schedules/images/logo.png" %}" class="logo" alt=""/>
    <!-- <h1 class="text-light">Securious</h1> -->

        <div style="margin-bottom: 50px; margin-top: -20px;">
            <br>    
            <h3 class="one">정보 보안이 궁금한</h3> 
            <br>
            <h3 class="two">당신을 위한 서비스</h3>
        </div>
        <div style="height: 100%;">
            <div class="btn-group mt-2 mb-4 bounce" role="group" aria-label="actionButtons">
                <a href="{% url 'schedules:carousel' %}"  class="d-block btn btn-outline-light btn-lg">시작하기 <i class="fas fa-external-link-square-alt ml-2"></i></a>

            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>

</body>
</html>

schedules/templates/schedules/introduce.html
{% extends 'schedules/base.html' %} {% load static %}
{% block content %}


<div class="row row-cols-1 row-cols-md-2 g-4" style="height:80vh; background-color: transparent;">
  <div class="col">
    <div class="card" data-bs-toggle="modal" data-bs-target="#introModal">
      <img src="{% static 'schedules/images/intro.jpg'%}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Securious 란</h5>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card" data-bs-toggle="modal" data-bs-target="#purposeModal">
      <img src="{% static 'schedules/images/purpose.jpg'%}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">기획 의도</h5>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card" data-bs-toggle="modal" data-bs-target="#strongModal">
      <img src="{% static 'schedules/images/strong.jpg'%}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">특장점</h5>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card" data-bs-toggle="modal" data-bs-target="#expectModal">
      <img src="{% static 'schedules/images/expect.jpg'%}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">기대 효과</h5>
      </div>
    </div>
  </div>
</div>

{% include 'schedules/modals.html' %}

{% endblock content %}

schedules/templates/schedules/jobs_group.html
<div>
    <div class="list-group">
        <div class="topbar">
        <h3 class="top-title" ><b>채용 공고 목록</b></h3>
        </div>

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="pills-normal-tab" data-bs-toggle="pill" data-bs-target="#pills-normal" type="button" role="tab" aria-controls="pills-normal" aria-selected="true">일반</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-alltime-tab" data-bs-toggle="pill" data-bs-target="#pills-alltime" type="button" role="tab" aria-controls="pills-alltime" aria-selected="false">상시</button>
        </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-normal" role="tabpanel" aria-labelledby="pills-normal-tab">{% include 'schedules/paged_jobs.html' %}</div>
        <div class="tab-pane fade" id="pills-alltime" role="tabpanel" aria-labelledby="pills-alltime-tab">{% include 'schedules/alltime_jobs.html' %}</div>
        </div>
  </div>
</div>

schedules/templates/schedules/modals/modal_intro.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Securious 란</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Securious는 Security + Curious의 합성어로써 정보보안 취업준비생들의 궁금증을 해결하기 위해 정보보안의 새로운 트렌드와 채용 정보를
        제공하는 통합 플랫폼입니다.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

schedules/templates/schedules/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'schedules:intro' %}"><img src="{% static 'schedules/images/logo2.png' %}" alt="" /></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'schedules:carousel' %}">홈</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schedules:introduce' %}">서비스 소개</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schedules:index' %}">보안 뉴스 & 채용 공고</a>
        </li>
      </ul>
    </div>
      </div>
    </div>
  </nav>

schedules/templates/schedules/paged_jobs.html
 <div class="pagination">
    <span class="step-links">
        {% if job_obj.has_previous %}
        <a href="?page=1"><i class="fas fa-angle-double-left"></i></a>
        <a href="?page={{ job_obj.previous_page_number }}"><i class="fas fa-arrow-circle-left"></i></a>
        {% endif %}

        <span class="current">
             {{ job_obj.number }} of {{ job_obj.paginator.num_pages }}
        </span>

        {% if job_obj.has_next %}
        <a href="?page={{ job_obj.next_page_number }}"><i class="fas fa-arrow-circle-right"></i></a>
        <a href="?page={{ job_obj.paginator.num_pages }}"><i class="fas fa-angle-double-right"></i></a>
        {% endif %}
    </span>
</div>

{% for job in job_obj %}
<a
href="{{ job.link }}"
target="_blank"
class="list-group-item list-group-item-action"
>
<div class="d-flex w-100 justify-content-between">
<h5 id="news_title" class="mb-1">{{ job.title }}</h5>
<small class="text-muted">{{ job.company }}</small>
</div>
<p class="mb-1">마감 기한 : {{ job.end_date }}</p>
<!-- <small class="text-muted">{{ job.time }}</small> -->
</a>

{% endfor %}